import logo from '../img/Logo.svg';
import menu from '../img/icons/Menu.svg';
import close from '../img/icons/Close.svg';
import bag from '../img/icons/Shopping-bag.svg';
import heart from '../img/icons/Favourites.svg';
import heartFilled from '../img/icons/Favourites-Filled.svg';
import slider1 from '../img/slider1.png';
import slider2 from '../img/banner-phones.png';
import phones from '../img/Phones.png';
import tablets from '../img/Tablets.png';
import accessories from '../img/Accessories.png';
import home from '../img/icons/Home.svg';
import arrowR from '../img/icons/arrowR.svg';
import arrowUp from '../img/icons/arrowUp.svg';

export const logoImg = logo;
export const menuImg = menu;
export const closeImg = close;
export const shopBagImg = bag;
export const heartImg = heart;
export const heartFilledImg = heartFilled;
export const bannerImg1 = slider1;
export const bannerImg2 = slider2;
export const phonesImg = phones;
export const tabletsImg = tablets;
export const accessoriesImg = accessories;
export const homeImg = home;
export const arrowRightImg = arrowR;
export const arrowTopImg = arrowUp;
